name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Changelog
        id: changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: ./.github/cliff.toml
          args: -o CHANGES.md --verbose --latest
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: wafstat

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.content }}
          artifacts: 'wafstat'
