name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: wafstat

      - name: Changelog
        id: changelog
        run: |
          cargo install git-cliff && git cliff --latest --output CHANGES.md

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          bodyFile: CHANGES.md
          artifacts: 'wafstat,CHANGES.md'
